#pragma once

enum class eGenes
{
	ADD_ANGLE_EVEN_BRANCH,
	ADD_ANGLE_ODD_BRANCH,
	SUBTRACT_ANGLE_EVEN_BRANCH,
	SUBTRACT_ANGLE_ODD_BRANCH,
	ADD_LENGTH_EVEN_BIO,
	ADD_LENGTH_ODD_BIO,
	SUBTRACT_LENGTH_EVEN_BIO,
	SUBTRACT_LENGTH_ODD_BIO,

};